# DISABLED: Docker push permission issues on organization repo
# Re-enable this workflow once GitHub Actions has proper write permissions
# to push to ghcr.io/BeehiveInnovations/zen-mcp-server
#
# This workflow builds and pushes multi-platform Docker images when releases are published
# It will be re-enabled once the organization permissions are resolved

# name: Docker Release Build
# 
# on:
#   release:
#     types: [published]
# 
# permissions:
#   contents: read
#   packages: write
# 
# jobs:
#   docker:
#     name: Build and Push Release Images
#     runs-on: ubuntu-latest
#     
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
# 
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
# 
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
# 
#       - name: Extract metadata
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ghcr.io/${{ github.repository }}
#           tags: |
#             # Version tags
#             type=ref,event=tag
#             type=semver,pattern={{version}}
#             type=semver,pattern={{major}}.{{minor}}
#             type=semver,pattern={{major}}
#             # Latest tag for latest release
#             type=raw,value=latest,enable={{is_default_branch}}
# 
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
# 
#       - name: Update release notes with Docker info
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const release = context.payload.release;
#             const dockerInfo = `
# 
#             ## 🐳 Docker Images
# 
#             This release is available as Docker images:
# 
#             **Multi-platform support:**
#             - \`ghcr.io/${{ github.repository }}:${release.tag_name}\`
#             - \`ghcr.io/${{ github.repository }}:latest\`
# 
#             **Quick start:**
#             \`\`\`bash
#             docker pull ghcr.io/${{ github.repository }}:${release.tag_name}
#             \`\`\`
# 
#             **Claude Desktop configuration:**
#             \`\`\`json
#             {
#               "mcpServers": {
#                 "zen": {
#                   "command": "docker",
#                   "args": [
#                     "run", "--rm", "-i", 
#                     "-e", "GEMINI_API_KEY",
#                     "ghcr.io/${{ github.repository }}:${release.tag_name}"
#                   ],
#                   "env": {
#                     "GEMINI_API_KEY": "your-api-key-here"
#                   }
#                 }
#               }
#             }
#             \`\`\`
#             `;
#             
#             await github.rest.repos.updateRelease({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               release_id: release.id,
#               body: release.body + dockerInfo
#             });